### ISSUE TITLE
Event loop and player death

### ISSUE THREAD

**Issue by CaveExplorer256** [MoeyyadQuresh/ChamberCrawler3000#18]
A good way to evaluate events per game loop would look like the following. (Just to confirm.)

Use the Player pointer and either do the logic in main.cc or a control() method. Player moves / attacks / picks up items first.

Iterate over all tiles and call tile->update(). This will call update() on all Characters which moves NPCs but will not do anything to Player as they've already moved.

Check for Player death. I've implemented Player->isDead() which is an easy break condition to use.

**Comment by CaveExplorer256** [comment]
Between tile->update() calls, we need to reiterate over all vectors again to run tile->resetCharUpdate().

update() will perform all actions for the game loop. To ensure it doesn't run twice on a Character which has moved, update() toggles a boolean inside Character to ensure it doesn't run again. The only way to retoggle the boolean and allow another update() next loop is to call tile->resetCharUpdate()

**Comment by BUNQNF** [comment]
Thank you. I'll go through main.cc again and ensure every points in the pdf covered. I'll post an issue if main.cc needs more helpers.

**Comment by BUNQNF** [comment]
isDead() is now called in main.cc to end the game as soon as HP falls below zero. (BTW I changed the isDead() from "return this->health < 0" to "return this->health <= 0").

If we are to use update() to move npc then it at least takes in a bool argument, so that main.cc can stop the npc from moving (the command f)

**Comment by CaveExplorer256** [comment]
For movement, we can use a static variable.
NPC::doMovement = true (or false);
