### ISSUE TITLE
Static variable initialization

### ISSUE THREAD

**Issue by CaveExplorer256** [MoeyyadQuresh/ChamberCrawler3000#28]
At the start of each new game we need the following in main.cc.
Merchant::hostileToPlayer = false;
NPC::doMovement = true; //Toggle this with the **f** command

**Comment by BUNQNF** [comment]
I'll add it into main.cc. Are they public variables to be initialized at the very beginning of the program in merchant.cc and npc.cc? Because I've already had bool pause = false to handle the f command.

**Comment by BUNQNF** [comment]
Now I'm setting NPC::doMovement to true and pause to false at the beginning. whenever f is inputed, pause=!pause and NPC::doMovement=!pause.
It this is wrong please tell me.

**Comment by CaveExplorer256** [comment]
Merchant and NPC need to be given values at the start of each game. I was going to do that in Merchant.cc and NPC.cc but realized that won't work when a game restarts. So instead they just declare the variables exist without any value.

Your _pause_ and _doMovement_ equals statements are good. We might be able to remove _pause_ and just use doMovement if the only effect of pausing the game is stopping NPCs from moving.

**Comment by BUNQNF** [comment]
OK, I'll remove pause.

**Comment by CaveExplorer256** [comment]
Sounds good :+1:
