### ISSUE TITLE
Getting player score

### ISSUE THREAD

**Issue by CaveExplorer256** [MoeyyadQuresh/ChamberCrawler3000#29]
There's a method, player->getScore() which automatically returns the amount of gold the player has and multiplies by 150% if race is a Shade.

**Comment by BUNQNF** [comment]
So when Character::printMessage is trying to get the amount of gold, is it better to call this->getScore or this->gold? For shade, (this->getScore)/1.5.

**Comment by CaveExplorer256** [comment]
Player->gold returns the amount of gold the player has.
