### ISSUE TITLE
override

### ISSUE THREAD

**Issue by BUNQNF** [MoeyyadQuresh/ChamberCrawler3000#44]
./characters/Character.h:36:15: error: no template named 'unique_ptr'; did you mean 'std::unique_ptr'?
  std::vector<unique_ptr<Item>> inventory;
              ^~~~~~~~~~
              std::unique_ptr
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2565:29: note: 'std::unique_ptr' declared
      here
class _LIBCPP_TYPE_VIS_ONLY unique_ptr
                            ^
In file included from main.cc:3:
In file included from ./Floor.h:8:
In file included from ./bg/Doorway.h:4:
./bg/PlayerExclusive.h:7:43: error: non-virtual member function marked 'override' hides virtual member function
  bool passable(const Character& c) const override; //Check if player
                                          ^
./bg/Background.h:10:16: note: hidden overloaded virtual function 'Background::passable' declared here: different qualifiers (none vs const)
  virtual bool passable(const Character&) = 0;
               ^
In file included from main.cc:3:
In file included from ./Floor.h:10:
In file included from ./bg/HorizontalWall.h:4:
./bg/Barrier.h:7:50: error: non-virtual member function marked 'override' hides virtual member function
  bool passable(const Character&) const noexcept override; //Never passable
                                                 ^
./bg/Background.h:10:16: note: hidden overloaded virtual function 'Background::passable' declared here: different qualifiers (none vs const)
  virtual bool passable(const Character&) = 0;
               ^
In file included from main.cc:3:
In file included from ./Floor.h:12:
./bg/FloorTile.h:8:50: error: non-virtual member function marked 'override' hides virtual member function
  bool passable(const Character&) const noexcept override; //Always passable
                                                 ^
./bg/Background.h:10:16: note: hidden overloaded virtual function 'Background::passable' declared here: different qualifiers (none vs const)
  virtual bool passable(const Character&) = 0;
               ^
In file included from main.cc:3:
In file included from ./Floor.h:15:
In file included from ./characters/npcs/Human.h:4:
./characters/npcs/NPC.h:6:19: error: expected class name
class NPC: public Player {
                  ^
./characters/npcs/NPC.h:13:16: error: 'attackChar' marked 'override' but does not override any member functions
  virtual void attackChar(Character& c) override;
               ^
./characters/npcs/NPC.h:14:26: error: only virtual member functions can be marked 'override'
  bool isHostile() const override;
                         ^~~~~~~~
./characters/npcs/NPC.h:15:17: error: only virtual member functions can be marked 'override'
  void update() override;
                ^~~~~~~~
./characters/npcs/NPC.h:16:2: error: expected ';' after class
}
 ^
 ;
In file included from main.cc:3:
In file included from ./Floor.h:15:
./characters/npcs/Human.h:14:33: error: only virtual member functions can be marked 'override'
  char getChar() const noexcept override;
                                ^~~~~~~~
In file included from main.cc:3:
In file included from ./Floor.h:16:
./characters/npcs/Halfling.h:15:33: error: only virtual member functions can be marked 'override'
  char getChar() const noexcept override;
                                ^~~~~~~~
In file included from main.cc:3:
In file included from ./Floor.h:17:
./characters/npcs/Merchant.h:16:33: error: only virtual member functions can be marked 'override'
  char getChar() const noexcept override;
                                ^~~~~~~~
./characters/npcs/Merchant.h:17:41: error: only virtual member functions can be marked 'override'
  void getHit(Character& c, int damage) override;
                                        ^~~~~~~~
./characters/npcs/Merchant.h:18:26: error: only virtual member functions can be marked 'override'
  bool isHostile() const override;
                         ^~~~~~~~
./characters/npcs/Merchant.h:19:35: error: only virtual member functions can be marked 'override'
  void modifyHealth(int quantity) override;
                                  ^~~~~~~~
In file included from main.cc:3:
In file included from ./Floor.h:18:
./characters/npcs/Elf.h:15:33: error: only virtual member functions can be marked 'override'
  char getChar() const noexcept override;
                                ^~~~~~~~
./characters/npcs/Elf.h:16:2: error: expected ';' after class
}
 ^
 ;
In file included from main.cc:3:
In file included from ./Floor.h:19:
./characters/npcs/Orc.h:13:52: error: only virtual member functions can be marked 'override'
  int getAttack(const Character& c) const noexcept override;
                                                   ^~~~~~~~
./characters/npcs/Orc.h:14:33: error: only virtual member functions can be marked 'override'
  char getChar() const noexcept override;
                                ^~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [main.o] Error 1

**Comment by CaveExplorer256** [comment]
Well, since we managed to compile, I'll mark this as fixed ;)
